Removed the CommsBus test because Jest isn't able to import wasm
I'm not quite sure why it can't find the `aimc_sim` module. If I refer
to `aimc_sim/aimc_sim.js` (the wrapper generated by wasm_bindgen) it
complains about a syntax error because the wrapper contains `import *
from "aimc_sim"`.

The error message:

```
FAIL  src/CommsBus.test.ts
  ● Test suite failed to run

    Cannot find module 'aimc_sim' from 'CommsBus.ts'

    However, Jest was able to find:
    	'./CommsBus.test.ts'
    	'./CommsBus.ts'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js', 'jsx', 'json', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      1 | import { Request, Response, Ack, Nack, GoHome, GcodeProgram } from './messaging';
      2 | import { Decoder, Packet, ChecksumFailed } from "anpp";
    > 3 | import * as wasm from "aimc_sim";
        | ^
      4 | import { Message, Direction } from './Message';
      5 |
      6 | interface Pending {

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (src/CommsBus.ts:3:1)
```